### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by RealYoti** [RealYoti/project-amber#2]
More important:
- [x] Choose a way to detect FW version inside payload (https://github.com/RealYoti/project-amber/commit/da99e9a2fa0289b1f5591054d6ef835aee0349ce)
- [x] Find `getiflist` offset value for 3.71+ FW versions (same as previous)
- [x] Find `ifunit` offset value for 3.71+ FW versions (got from SKGleba)
- [x] Find `in_control` offset value for 3.71+ FW versions (got from SKGleba)

Less important:
- [ ] Add 3.55 offsets into offsets.js
- [ ] Add 3.57 offsets into offsets.js
- [ ] Add 3.60 offsets into offsets.js
- [ ] Add 3.61 offsets into offsets.js
- [x] Add 3.67 offsets into offsets.js (got from SKGleba)
- [x] Add SD2VITA support (https://github.com/RealYoti/project-amber/commit/834b2c13e4dfb816bc983a2c8f8bf5fc7199a9a4)
